name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 20 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          days-before-stale: 30
          days-before-close: 5
          stale-issue-label: 'no-issue-activity'
          any-of-labels: 'bug'
          exempt-issue-labels: 'Confirmed'

      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because it has been confirmed as a bug but still been opened 90 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity.'
          days-before-stale: 90
          days-before-close: 30
          stale-issue-label: 'no-issue-activity'
          only-issue-labels: 'bug,Confirmed'
